name = "baby-rudin-project"
version = "0.1.0"
defaultTargets = ["baby-rudin-project"]

[[lean_lib]]
name = "BabyRudinProject"

[[lean_exe]]
name = "baby-rudin-project"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
